modLoader="javafml" #mandatory
loaderVersion="[41,)" #mandatory 
license="MIT License"

[[mods]] #mandatory
modId="additional_lights" #mandatory
version="2.1.4" #mandatory
displayName="Additional Lights" #mandatory

updateJSONURL="https://gist.githubusercontent.com/mgen256/59abe85e7950f2319e7538afe2f910ba/raw"
displayURL="https://www.curseforge.com/minecraft/mc-mods/additional-lights" #optional
logoFile="logo.png" #optional
authors="mgen256" #optional
description='''
'''

[[dependencies.additional_lights]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[41,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.additional_lights]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
